-- CRIAÇÃO COMPLETA DA TABELA LEADS
-- Copie e cole todo este código no Editor SQL do Supabase.

-- 1. Cria a tabela se ela não existir
CREATE TABLE IF NOT EXISTS leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Adiciona as colunas necessárias (se não existirem)
-- Usamos "IF NOT EXISTS" (lógica aproximada) ou ALTER TABLE simples que pode falhar se já existir,
-- mas a forma mais segura em script simples é tentar adicionar ou garantir que a tabela tenha estes campos.

-- Abaixo estão comandos ALTER TABLE que adicionarão as colunas caso a tabela tenha acabado de ser criada.
-- Se as colunas já existirem, o Supabase pode retornar erro "column already exists", o que é inofensivo
-- se você apenas quer garantir que elas estejam lá.

-- Campos do Formulário
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "Nome completo" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "Clinica" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "Localizacao" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "WhatsApp" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "Contactos novos / dia" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "Equipa de atendimento" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "Faturamento Mensal" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "Maior dificuldade hoje?" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "Pretende investir agora?" text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS "SMS Enviada" boolean default false;

-- 3. Habilita Row Level Security (opcional, mas recomendado)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- 4. Cria uma política para permitir inserção pública (necessário para o formulário funcionar sem login)
CREATE POLICY "Permitir inserção pública de leads" 
ON leads FOR INSERT 
WITH CHECK (true);

-- 5. Cria uma política para permitir leitura apenas para o painel (ajuste conforme necessidade)
-- Por enquanto, permitimos leitura se for o mesmo usuário ou pública se simplificado, 
-- mas para admin geralmente se usa a role service_role ou autenticação específica.
