-- CÓDIGO PARA CRIAR A TABELA DO ZERO
-- ATENÇÃO: Isso apagará todos os dados existentes na tabela 'leads' se ela já existir.

DROP TABLE IF EXISTS leads;

CREATE TABLE leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    "Nome completo" text,
    "Clinica" text,
    "Localizacao" text,
    "WhatsApp" text,
    "Contactos novos / dia" text,
    "Equipa de atendimento" text,
    "Faturamento Mensal" text,
    "Maior dificuldade hoje?" text,
    "Pretende investir agora?" text,
    "SMS Enviada" boolean default false
);

-- Habilitar segurança e permitir inserções públicas (para o formulário funcionar)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserção pública" 
ON leads FOR INSERT 
WITH CHECK (true);

-- Política para permitir leitura (opcional, útil para você ver os dados no painel se estiver testando)
CREATE POLICY "Permitir leitura pública" 
ON leads FOR SELECT 
USING (true);
